# Site settings
title: "Syarif Resume"
description: "A resume template for Jekyll and GitHub Pages sites."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "false"
resume_name:                    "Syarif Nur"
resume_title:                   "Android Developer"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "syarif.nur92@gmail.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "-"
resume_contact_address:         "-"

resume_header_contact_info:     "742 Evergreen Terrace, Springfield • 555-7334 • lisasimpson@youremailaddress.com"
display_header_contact_info:    "false"

resume_header_intro: "<p>I am a software developer, primarily focused on building web applications using Laravel. Recently, I have expanded my skill set to include mobile app development, utilizing Flutter for cross-platform app development and Android Kotlin for native Android applications. My expertise lies in integrating Laravel as the backend for these mobile applications, ensuring robust and efficient communication between the frontend and backend systems. I am passionate about continuously learning and exploring new technologies, with a keen interest in staying updated on the latest advancements in software development. My goal is to leverage my experience in Laravel and mobile app development to create innovative and user-friendly solutions for a diverse range of projects.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       false
resume_section_projects:        false
resume_section_skills:          false
resume_section_recognition:     false
resume_section_links:           false
resume_section_associations:    false
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/syarif-nur/"
  # resume_twitter_url:           "http://twitter.com/jglovier"
  # resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/syarif-nur/"
  # resume_instagram_url:         "insert your Instagram URL here"
  resume_website_url:           "http://syarif-nur.github.io"
  # resume_medium_url:            "https://medium.com/@jglovier"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
